name: CI Build and Upload

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  build-and-upload:
    if: ${{ github.event.label.name == 'CI:TriggerBuild' }}
    runs-on: self-hosted

    steps:
      - name: Check repository
        id: check_repo
        run: echo "::set-output name=repo::${{ github.event.pull_request.base.repo.name }}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-ethereum:latest
