---
name: Trigger Workflow

on:
  workflow_run:
    workflows: ["CI Build and Push"]
    types:
      - completed

jobs:
  trigger-actions:
    runs-on: self-hosted

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ secrets.DOCKERHUB_USERNAME }}',
              repo: 'zkevm-node',
              workflow_id: 'provision.yml',
              ref: 'main'
            })
